---
title: "项目建议书"
author:
  - 丁凡宇
  - 金毅铭
  - 邓朋
  - 胡宵宵^[Equal Contribution, Fudan University, 17302010077(xxhu17@fudan.edu.cn)]
  - 俞继涛
  - 宋怡景
date: "2020年10月14日"
documentclass: ctexart
output:
  
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    keep_md: yes
    keep_tex: yes
    toc: yes
subtitle: 项目管理卓班小组项目建议书作业
classoption: hyperref, a4paper

---
```{r eval=FALSE, include=FALSE}
tinytex::install_tinytex()
```
\newpage
# 项目背景
从古代以来，人类就发展出了多种娱乐方式，而这些娱乐方式，都是和当时的生产力相关的。另一方 面，随着科学技术的发展，人类也制造了许多机器来提高计算能力，从算盘到查尔斯·巴贝奇设计的差分 机，再到电子计算机。虽然世界上第一台电子计算机ENIAC在1946年就已经被发明，但是受制于诸多因 素，例如早期电子计算机不存在软件，计算能力相比之下较为低下，相对容易出现故障以及计算时间的 宝贵性等因素，早期的电子计算机上并没有发展出电子游戏。但是，娱乐是人类的一个不可否认的需 求，而有些娱乐方式对于进行运算的能力是有需求的，如果运算能力不足，这些游戏不说不可能，至少 不能很好地运行。在这样的前提之下，利用电子计算机的运算能力来进行娱乐，让之前被认为不可能很 好地运行的游戏被运行起来，也是生产力发展的必然。而电子计算机相关科学技术的发展，至少在20世 纪，还是非常迅速的。比如从电子管到晶体管，从晶体管到中小规模集成电路，以及从中小规模集成电 路到大规模和超大规模集成电路的发展;又比如我们都知道的摩尔定律:每18个月，集成电路芯片上所 集成的电路的数目翻一倍。在摩尔定律代表的发展速度之下，电子计算机的性能提升和相对之下的使用 代价的下降，则给予了电子游戏诞生的条件。  
在1972年，“Pong”被创造了。虽然画面非常简陋，游戏的玩法在今天看来也非常一般，但这却是一 个划时代的大事件:它的被创造，标志着电子游戏的诞生，而它也自然成为了世界上第一个电子游戏。 从“Pong”被创造出来以来，电子游戏就逐渐地发展了起来。一方面，电子计算机的性能仍然在提升;另 一方面，编写游戏软件也更为容易了，无论是从机器语言到汇编语言再到高级语言的发展，还是从行编 辑器到全屏幕编辑器的发展，以及从面向过程到面向对象的编程思想的发展，都让实现相同内容的游戏 软件更加容易开发了。一些游戏引擎的编写，更是使得游戏开发效率提高了，减少了开发者在重复造轮 子上所花费的时间。例如本项目选择的Unity，就是一款著名的引擎。  
虽然经历过雅达利崩溃等挫折，但是在上文提到的正面因素，以及世界范围内经济发展和全球化的推 动之下，电子游戏产业还是逐渐发展壮大。到了现在，电子游戏已经成为了第三产业的重要组成部分。 在今天，电子游戏相关产业创造了不少的国内生产总值并且提供了不少的就业岗位，为我国和世界做出 了巨大贡献。而在电子游戏的逐步发展之中，又产生了多种游戏类型，而这些不同的电子游戏类型也有 不同类型与数量的受众。在这些电子游戏类型之中，2D平台动作游戏是一种不但曾经颇为流行，有着广 大的受众基础，而且近年来也重新流行，证明了其仍然具有丰富的生命力的游戏类型。而游戏“空洞骑 士”(原名为“Hollow Knight”)就是近年来，重新流行的2D平台动作游戏之一。它的成功雄辩地证明 了，质量过硬的2D平台动作游戏仍然是有不小市场的。但是，这一游戏也不可能是完美的，仍然有一些 玩家的需求没有实现，而该游戏的制作组也没有及时提供功能以满足玩家的需求，又或者推出新的作 品。所以，在考虑到这一现状后，我们就准备自行开发一款粉丝向复刻游戏。当然，除了尽可能复原出 原作已有的内容，我们还会自己增加一些新的内容，以满足之前玩家提出的需求。  

# 项目介绍

 本项目所需要实现的内容，既包含了复现原游戏已经实现的旧的内容，也包含了自己在根据原游戏复
现出的内容的基础上再增加新的内容。具体需要实现的内容见下详述:  

## 在复现原游戏内容时需要完成的任务
这些内容是游戏的基础，如果没有这些基础，改进也就如同空中楼阁一般无从谈起。只要这些基础实
现得不好，我们的游戏也会与原作产生差别，而这些差别则可能让我们的游戏失去吸引力。具体来看，
我们需要复现的内容包括:  

### 主角行为
主角行为是玩家操作的直接反馈，如果主角行为不能有一个好的实现，那么对玩家的操作所进行的反
馈也会出现问题。考虑到游戏本身就是一种反馈机制，所以可以说，主角行为的复现优劣对能否完好复
现至关重要。具体来看，这主要要通过我们编写的状态机来实现。如果状态机编写好了，那么行为也就
完好复现了。而如何设计和编写状态机则是具体的技术问题，在此不作详述。  

### 敌人行为
敌人行为和主角行为有一定的相似之处，不过也有不同的地方。具体来看，敌人是不需要接受玩家输
入的，这就与主角行为产生了区别。同时，在玩家不操控的时候，主角是不进行行动的，但敌人却不能
以同样的方式来进行处理，否则因为之前所说的，敌人根本不可能接受玩家的输入，就会导致这一游戏
无法正常运行的状况出现。所以，敌人行为需要有一套专门的行为逻辑，而这一问题我们计划通过在不
同的状态机之间切换来实现。不过，除了这两个问题以外，也没有什么太多的区别，只要加以注意，那
么在可以做好前者的基础上，它就被转变成了一个已经解决的问题了。毕竟，状态机的编写的基本思路
是共通的，和主角行为的状态机之间，主要区别在于状态机的条件不同。  

### 菜单和存读档功能
菜单功能是非常重要的，因为这提供了一个在游戏过程中调整参数的方式。诚然，我们可以通过其他 方式在开始运行时传入相关参数，但是这种方式并不能让玩家便利地调整参数，同时也不能在游戏进行 过程中动态调整。而存读档功能则更为重要，如果没有存读档功能，那么玩家如果想要体验完整的游 戏，就必须一次性完成游戏，中途不能退出游戏。考虑到这一游戏时间不可能太短让玩家即使不需要存 读档功能也能从头开始很快进行游戏到此前进度——否则游戏就根本无法包括多少内容，那么存档功能 基本就可以说是必须的。诚然有一些其他技术手段可以在关闭电子计算机的情况下也能让游戏不中断而 继续下去，但是我们不可能也不应该要求用户掌握这些技术手段，给用户增加额外的负担。所以，菜单 和存读档功能的实现就颇为重要。  

### 图形用户界面
在现代，对于绝大多数程序来说，传统的CLI已经被抛弃了，GUI成为了新的界面一般标准。CLI虽然 有利于执行批量处理等优势，但是考虑到电子游戏，尤其是2D平台动作游戏本身的特色，我们不认为玩 家在一般情况下会有这样的需求。相比之下，GUI容易上手操作的优点就更好地体现了出来，更加适合 这一场景。而且，原作也选择了GUI而不是CLI，选择GUI更有利于原作玩家上手，同时GUI越相似，这 一优点就越发显著。  


### 地图和素材处理
虽然不实际编写代码，但是地图和素材处理仍然是重要的工作。现在已经不是最初只要有电子游戏玩
就可以的时代了，现代的电子游戏的画面也是非常重要的。而为了尽可能保持相似性，就需要对于地图
和素材的处理。另外，对于它们的处理，也可以让我们积累经验，而这些经验在添加新内容，尤其是添
加新地图时，可能可以被应用到项目中来。  

## 在根据原游戏的基础上需要添加的新内容:
 具体来说，主要包括两个方面:一方面是我们自定义的新地图和关卡，另一方面则是我们添加的新机制。下面对每一方面进行详述。  

### 自行定义的新地图和关卡
新的关卡是我们的游戏在游玩上，与原作最本质的区别。在已经有了主角和敌人行为的基础上，如果 我们想要充分让玩家体验这些成果，那么就需要关卡来给予玩家体验他们的机会。而新的关卡也自然需 要新的地图来让玩家感觉到新鲜感，对游戏产生更大的兴趣。另一方面，新的关卡也可以表现新的故 事，让玩家体验到新的剧情，而剧情一直都是对游戏的重要评价标准。例如“异域镇魂曲”，就因为剧情 杰出而至今仍然被提起。而对新的关卡与剧情的讨论，也可以引起一些玩家对本游戏的关注。  

### 添加的新机制
新的机制可以增加游戏的趣味性，同时也可以促进玩家对游戏投入更多的时间，又或者在社交媒体上
提及本游戏。具体来说，就是增加排行榜和多人闯关模式。增加排行榜具体来说，就是记录所有玩家完
成每一个关卡的时间，并且将其排序并展示用时最少的一些玩家所花的时间以及本机玩家完成所花的时
间。设计排行榜可以利用人普遍存在的竞争心理，让玩家与自己在现实中或网络上的好友进行比较，而
这有利于增加本游戏的曝光度，也就可以使得更多人对本游戏产生一定程度上的关注，从而可以进一步
增加销量。同时，这也可以促进玩家就如何减少通关时间展开交流，而这些可能产生的交流也和之前提
到过的与好友进行比较同理，也是可以增加销量的。另一方面，这也可能是玩家的需求之一，可以看到
自己在玩家中的相对排名，知道自己的游戏水平大约在本游戏的所有玩家中处在的位置。而对于增加的
多人闯关模式的具体介绍，就是允许多个玩家分别操控自己的角色，进行对关卡的游玩。一方面，多人
模式可以鼓励玩家去寻找其他玩家一起游玩，并且展开与深化合作，这同样也可以如同之前的分析一样
增加销量;而另一方面，增加玩家也可以降低游戏的难度。根据兰彻斯特平方律，玩家即使只增加一
个，玩家的战斗力也翻了四倍。考虑到原游戏的难度并不是很低，多人模式也可以作为一个手段，让无
法在单人模式下操作发挥出足以通关游戏的战斗力的玩家也有可能通关游戏来获得一些游戏体验，从而
增大他们可能的购买游戏的欲望。  

## 测试
测试不产生任何内容，但是测试仍然是软件开发过程中一项重要的环节。要开发出没有bug的软件， 一种途径是证明，但是这种方法非常困难，应用范围也不广;而另一种途径，就是进行足够的且尽可能 涵盖各个方面的测试。在本项目中，我们会在每个模块开发过程中进行单元测试，以期尽早发现bug并 修复;而在最后集成之后，也会进行集成测试，来测试模块之间交互是否存在bug。  

# 可行性分析

## 市场可行性分析

### 市场背景
动作游戏是电子游戏类型的一种，它强调玩家的反应能力和手眼的配合。动 作游戏的剧情一般比较简单，主要是通过熟悉操作技巧就可以进行游戏。这 类游戏一般比较有刺激性，情节紧张，声光效果丰富 [维基百科]。2D 动作 游戏出现的时间比较早，截至目前也有大量的游戏爱好者。《马力欧系列》 最早发布于上世纪 80 年代，至今销量已达五亿 6000 万份，是史上销量最 高的电子游戏系列。目前动作游戏继续火热的原因主要有以下几个原因。  
动作类玩法是电子游戏中较为常见的一种类型，在广大游戏玩家中有着良 好的口碑。近年来，网络小说的空前普及，武侠、仙侠类小说都具有庞大的 读者群体，这也为角色扮演类游戏奠定了良好的玩家基础。不少玩家偏爱探 险类、解密类和剧情类游戏，动作类玩法能够将众多游戏特点进行整合，让 不同类型的玩家能够在游戏中寻找不同的乐趣。  
动作游戏作为市面上最常见的游戏类型，游戏的核心玩法已基本确立。开 发者使用现成的游戏系统，既能保证产品的耐玩度，又能提高游戏粘性，容 易获得玩家市场的认可。目前动作游戏的框架比较成熟，游戏模式丰富多 样。一类游戏能够通过切换游戏素材，转换游戏背景的方式转变为一款新的 动作游戏，游戏开发成本可控，开发产品多样化。  
与策略类游戏不同，动作游戏战斗和任务系统高度自动化，玩法上手简单， 不需要占用玩家太多精力，对玩家操作和策略要求较低，能利用玩家的碎片 时间。与网络游戏不同，动作类游戏强调玩家对游戏人物的操作与掌控，尽 管在游戏中会存在一定的挑战，但是动作冒险类游戏最吸引人的便是挑战 成功后的成就感。

### 竞品特点
当前市场上动作冒险类游戏种类繁多，比较热门的游戏有，《空洞骑士》、《死 亡细胞》等。这类游戏被称为类银河战士恶魔城游戏。这类游戏中通常有可 供玩家探索的大型相连世界地图，但是进入地图某处的特定地点往往会有 门或其他障碍物限制玩家，只有当玩家在游戏中获得特殊道具、工具、武器 或能力后才能通过。这些新的提升还能帮助玩家击败更高难度的敌人并找 到捷径和秘密区域，包括经常回顾已经探索过的地图区域。银河恶魔城游戏 通过这样的设计使故事和关卡设计整合得更紧密，以精心设计的关卡和角 色控制来鼓励玩家探索和实验，使之更投入自己的角色。  
本次项目的主要参考对象为空洞骑士。《空洞骑士》是一个 2D 动作冒险类 游戏，2017 年 2 月发售，至 2019 年 2 月销量已经突破 280 万份。《空洞骑 士》发售后获得普遍好评，任天堂 Switch 获得了 90 分的媒体平均分数。尽 管当前游戏趋向 3D 化，但是《空洞骑士》的成功说明 2D 动作冒险类游戏 的受众还是有很大的份额和市场。  
《空洞骑士》的特点多样化，实现了许多游戏亮点的组合。  
首先，《空洞骑士》展现了传统动作游戏的魅力。空洞骑士游戏的操作与大 多数游戏一样，通过简单的上下左右控制方向，简单的攻击方式和特殊的技 能。在这简单的操作背后是复杂的冒险地形，困难的敌人挑战以及多样的探 索方式。游戏内将会 “学习” 如何使用这些简单操作的组合击败各种各样的 敌人。尽管游戏难度偏高，但是游戏乐趣以及成就感足以吸引一大批用户玩 家。  
其次，游戏设计剧情为玩家需要从细节推断游戏背景。与许多游戏不同，《空 洞骑士》并没有直接交代游戏背景，而是通过游戏进程的展开，一步一步告 诉玩家真相，吸引玩家不断探索剧情。更重要的是，游戏的结局是多样化的， 不同的玩家由于游戏进度、游戏选择不同将产生不同的结局。玩家为了更好 的结局将需要做出更大的努力。  
最重要的是，游戏具有一定的开放性特色。作为类银河战士恶魔城游戏，地 图的探索将是游戏的一大特色。《空洞骑士》的探索过程具有很大的自由性， 游戏剧情将不会强制玩家的游戏进程，相反，游戏的剧情只会引导游戏的结 局，但是游戏中，玩家将遇到多种多样的道路选择问题。这种问题将导致每 个人的游戏过程不尽相同。有些玩家喜欢探索而选择了危险与挑战并存的 道路;有些玩家喜欢炫酷的场景而选择了充满色彩的道路;有些玩家为了探 索剧情而选择了故事推进的道路。不同的玩家将有不同的体验，这将是游戏 发展的方向与目标，所以《空洞骑士》在这方面的表现是足够的。  
通过分析《空洞骑士》的特色，项目的开发目标也得以明确。动作冒险类 游戏核心的功能是主角的操作，所以游戏的重要开发目标是实现包括任务 控制，技能释放，环境交互的动作机制。在地图和剧情设计上，我们也将保 持自由度和开放性的特色，创建更多更加有趣的关卡与地图。

### 项目优势

#### 互联网扩展

《空洞骑士》原作亮点特色多样，是非常受欢迎的作品。但是我们的 开发团队在分析了游戏特色后也找到了一些游戏的欠缺之处。游戏的模式是单机游戏，这就导致了游戏玩家将产生一定的孤独感。更重要
  的是，游戏难度偏大，许多重要的关卡需要大量的时间进行重复挑战。  
出于这方面的考虑，我们将为我们的项目中添加互联网扩展。例如， 单纯的闯关带来的挑战比较单一，我们将创建游戏排行榜，将游戏玩 家以多种方式进行排序，吸引玩家进行相互挑战，增加游戏乐趣。我 们也将考虑增加多人联级功能，面对强大的敌人，我们允许玩家组队 挑战，一方面促进玩家之间的交互，另一方面减少游戏的孤独感，增 强游戏性。

#### 自定义扩展
项目虽然偏复刻类型，但是我们会进行更多方面的扩展。例如，在地 图探索方面，我们将设计自定义关卡，增加探索乐趣;在人物技能方 面，我们将对任务动作与技能效果进行创新与多样化，增加游戏操控 的选择性;剧情方面我们将设计更加有趣的扩展剧本，为动作冒险游 戏粉丝带来不一样的体验。

## 技术可行性分析

### 方案概述
《Hollow Knight》游戏原作是⼀一款基于游戏引擎Unity开发的2D平台跳跃类游戏，由于该引擎开发 ⼯工具链成熟完善、教程丰富、易易于部署，其上⼿手⻔门槛不不⾼高对新⼿手开发者⼗十分友好，考虑到该引擎的精细 程度、优化程度、可扩展性及经济性，本项⽬目决定同样采取该引擎进⾏行行开发。此外，原作画⾯面特效均由 全⼿手绘⻛风格2D美术素材组成，对后期的图形渲染效果⽆无开发需求，使得团队可以对游戏本身的素材进⾏行行 处理理及美术外包的形式解决其他美术需求问题(⾳音乐、⾳音效等素材同理理)，因此，团队六⼈人可以在有限 的开发时间内专注于游戏玩法逻辑的开发。对于团队协作开发⽅方式，本项⽬目将采⽤用基于Git⼯工具的敏敏捷式 开发流程，根据前期计划的各个进度⾥里里程碑碑进⾏行行合作开发，且在项⽬目开发的过程中，由于游戏开发项⽬目 的特殊性，团队将不不断组织部分外部⼈人员对已有开发内容进⾏行行测试，并及时根据反馈对项⽬目进⾏行行调整和 优化。  
主要技术点:
- Unity引擎工具链的使⽤
- 游戏逻辑脚本的组织与实现
- 原创关卡设计
- 联网功能模块
- 图像/视频/音频处理工具的使用

### 项目成员现有积累
本项目⼩小组成员均来⾃自复旦⼤大学计算机科学与技术学院软件工程专业(卓越⼯工程师计划)，在经过 大学期间的不不断学习和训练后均已掌握了了扎实的编程基础，且由于专业的特殊性，成员均有着丰富的软 件合作开发经历，熟悉基于Git的合作开发流程，掌握项⽬目所需的各类软件开发设计模式。同时，复旦大 学丰厚的⼈人⽂文底蕴和良好的校园氛围给予了了项⽬目团队较⾼高⽔水平的鉴赏审美和设计能⼒力力，且队伍均衡的男 ⼥女女⽐比例例为对项⽬目内容的评估提供了了客观全⾯面的思考视⻆角。

- 对于游戏引擎的使⽤，项目成员曾经使用Unity引擎进⾏过小型游戏项目的开发，熟悉引擎内各类 ⼯具的使用⽅方法，了解此类型游戏整体的模块划分和开发流程，能够设计项⽬整体的程序架构和功 能分配、把控游戏内容的开发进度。
- 对于游戏内地图关卡设计与⼈人设计，项⽬成员有着丰富的游戏经历，能够从已有的成熟的游戏设 计范例中汲取经验制作难易度适中但能够有效驱动玩家的游戏内容。   
- 对于联⽹功能模块，项⽬成员曾经进行过小型web项⽬的开发，熟悉软件不同客户端之间的⽹络通 信⽅法和与前端的数据交互实现。   
- 项目成员能够熟练使用项⽬需要的各类图像/视频/⾳频处理工具(如Photoshop、AE等)。

### 关键技术分析

#### Unity游戏引擎基础工具链
- 引擎介绍
Unity也称Unity3D，是由 Unity Technologies 公司开发的一个让玩家轻松创建诸如二、 三维视频游戏、建筑可视化、实时二、三维动画等类型互动内容的多平台的综合型游戏开发⼯具。
- 特性优势
  - 跨平台: 游戏开发者可以通过不同的平台进行开发。游戏制作完成后，游戏无需任何修改即可直接一键发布到常用的主流平台上。Unity游戏可发布的平台包括 Windows、Linux、MacOS X、iOS、Android、Xbox360、PS3 以及 Web 等。跨平台开发可以为游戏开发者节省大量时间。以往游戏开发中，开发者要考虑平台之间的差异，比如屏幕尺寸、操作方式、硬件条件等，这样会直接影响到开发进度，Unity将大幅度减少移植过程中不必要的麻烦。
  - 综合编辑:  Unity的用户界面具备视觉化编辑、详细的属性编辑器和动态游戏预览特性。Unity 3D 创新的可视化模式让游戏开发者能够轻松构建互动体验，当游戏运行时可以实时修改参数值，方便开发，为游戏开发节省大量时间。
  - 资源导入: 项目可以自动导入资源，并根据资源的改动自动更新。Unity 3D 支持几乎所有主流的三维格式，如 3ds Max、Maya、Blender 等，贴图材质自动转换为 U3D 格式，并能和大部分相关应用程序协调工作。
  - 物理特效: 物理引擎是模拟牛顿力学模型的计算机程序，其中使用了质量、速度、摩擦力和空气阻力等变量。Unity 3D 内置 NVIDIA 的 PhysX 物理引擎，游戏开发者可以用高效、逼真、生动的方式复原和模拟真实世界中的物理效果，例如碰撞检测、弹簧效果、布料效果、重力效果等。
  - 脚本语言: Unity 3D 集成了 MonoDeveloper 编译平台，支持 C#、JavaScript和Boo三种脚本语言，其中 C# 和 JavaScript 是在游戏开发中最常用的脚本语言。
- 技术难点
  - 小组内部分同学无Unity引擎使用经验。
- 解决方案
  - 项目组会在项目开始前为组员们提供Unity游戏引擎的入门教程与项目练习，使得组员在两周的时间内能够掌握项目所需工具链的基础操作，之后再进行项目正式内容的具体开发。

#### 游戏逻辑脚本的组织与实现
- 技术说明
  该项目中，开发者需要使用C#脚本实现游戏的大部分逻辑控制，例如主角的移动控制、技能释放、动画切换、环境交互及机关触发、敌人逻辑、菜单交互等。
- 技术难点
  - 主角角色如何通过静态美术素材实现流畅的动画切换
  - 敌人行为逻辑如何组织
  - 如何减少地图中大量可互动要素的编程负担
- 解决方案
  - 对于主角角色的动画切换，可以利用Unity内部工具链中的Animator（动画控制器）能够改变物体贴图的机制，提前为主角角色设置不同状态下的一系列动作图片序列，通过控制图片播放顺序的方式实现主角角色动画的流畅切换。
  - 对于敌人行为逻辑的组织，可以为每种敌人均创建多个不同的“状态机”，并未这些不同的状态设置特定的切换顺序与切换条件。
  - 对于机制相同的地图元素，将每一类型的原型模板（prefab）打包，每次将一模板单元添加到地图中时再进行细节参数的具体调整。
  
#### 原创关卡设计
- 技术说明
  对于每一种特定类型的游戏，其所有的关卡设计都需要为其核心游戏机制服务，地图与场景就是整个游戏的舞台，任何的玩法、战斗、剧情等方面都需要借助舞台来展现。在关卡开始设计之前，项目需要统一关卡的设计理念与“范围”，防止关卡内容与游戏主题和核心机制的割裂。
- 技术难点
  如何制定关卡设计原则，防止关卡内容与游戏主题和核心机制的割裂感。
- 解决方案
  - 《Hollow Knight》原作为传统的2D类银河恶魔城动作游戏，该类型对地图规划和关卡设计有着成熟的设计思想内核：在传统横版动作过关游戏的基础上加入可自由探索的2D沙盘地图，装备、道具和能力升级等RPG要素，并且以这些奖励作为驱动力驱使玩家不断对地图和剧情进行进一步探索。
  - 在制作原创关卡时，需要根据主角技能和道具的齐全程度对地图进行划分，在此基础上对特定的技能或是装备进行有针对性的关卡设计，依据游戏进度设计出由前期较简单而具有启发性的关卡，到后期较复杂而具有挑战性的关卡。

#### 联网功能模块
- 技术说明
  原作专注于沉浸式的单人剧情体验，而本项目中希望能够提供联网服务以扩充游戏内容，如多角色联机模式、合作互动要素、在具有挑战性的平台跳跃关卡区域提供排行榜功能等。
- 技术难点
  如何在Unity引擎中调用网络通信服务。
- 解决方案
  在服务端搭建服务器后使用Socket与Unity客户端进行数据交互。
  
#### 结论
  根据之前所进⾏的讨论与论证，该项⽬技术可⾏性⾮常高，在限定时间内能够实现较高的产品完成
度。  

# 项目干系人分析
# 风险分析

## 需求阶段风险分析
需求分析对于一个项目的成功有着至关重要的影响，统计表明，所有失败的软件项目中有一半是直接由不合格的需求工程导致的。因此，做好需求工程则成了一个自然而然的要求。然而，在需求的获取、需求的管理以及需求的验收等阶段都存在出现问题的可能，下面便对需求阶段可能存在的风险进行分析。  

### 缺少利益相关方的参与
系统的利益相关方是指能够直接或间接地影响系统需求的个人获组织。在本次项目中，利益相关方主要包含用户、开发者、项目负责人、项目经理等。在需求获取阶段，如果缺少某些利益相关方的参与，会使得需求的收集不完整，从事使后续的开发过程中引入新的需求或者遇到重大的需求变更，甚至使开发出的软件无法得到市场的认可。为此，需要在需求收集阶段尽可能的收集所有利益相关方的需要以及她们项目件的期望，从而降低该风险。
需求无法达成一致  
不同的利益相关者对于项目的期望有着不同的见解。在软件开发早期，应当使不同的利益相关者对需求的理解达成一致，避免因利益相关者对需求的不一致理解而给软件开发带来阻碍。为此，可以召集利益相关者参与的需求讨论会，消除存在的需求理解不一致的问题。

### 快速变化的需求
项目的利益相关方对项目的期望可能会随着时间不断的发生变化，而市场的不确定性以及技术的发展可能会使项目的目标发生变化，这些频繁变更的需求，可能会对项目的进度、成本、质量造成巨大的影响。为此，需要同利益相关方提前约定需求的范围，如果有频繁的需求变更，应当进行变更影响分析，尽量减少不必要的变更，如果一定要变更，应当协商增加项目的成本和开发周期。

### 需求镀金
镀金需求，是指哪些锦上添花的需求。完成了镀金需求，可能会使用户满意度提高，不完成也不会使用户的不满意度增加。镀金需求的存在可能会对软件开发的进度带来一定的影响。为此，针对每条需求，让客户或用户进行不满意度分析，以此确定需求实现的优先级，对于镀金需求，可以商定实现的时机。

### 没有需求验收标准
每条需求，都应当有相应的可量化的验收标准。这样，在验收需求是否全部满足时，可以有严格的标准做出没有异议的判断。因此，在完整收集利益相关方的项目需求的基础上，也要同她们商定相应需求验收标准，在需求做出变更或者增加时，相应的验收标准也要做出更改。

## 软件设计阶段风险分析
在进行软件设计时，由于设计人员对需求的不正确理解甚至不熟悉，以及受到设计人员自身能力的限制，可能会导致项目的设计出现问题，从而影响整个项目的开发进程以及质量。

### 软件设计过于简单
软件设计人员的能力欠缺可能导致软件的设计过于简单，导致软件无法满足需求，可能会导致重新设计或实现，进而导致软件无法按期完成，增加项目开发周期的同时也会增加项目的开发成本。为此，在软件设计完成后可以组织相关人员对设计方案进行评审，尽量减少设计方面的问题。

### 软件设计过于复杂
虽然良好的软件设计可以大大节省软件的开发时间，提高软件的可拓展性和可维护性，但是盲目的追求软件设计可能会导致软件设计过于复杂。软件设计复杂度提高的同时必然会导致工作量的增加，这会给开发人员增加一些不必要的工作，大大影响软件的开发效率。为此，在软件设计的过程中也要避免过度设计，做好设计和软件复杂度之间的平衡。

### 软件设计质量低下
由于软件设计人员的能力不足，软件的设计方案质量可能无法令人满意。低下的设计质量可能会带来重复的设计和实现，不软件的可拓展性和可维护性也会不尽人意。这会增加开发人员的工作量，而后续的软件维护工作也较难进行。为此，需要提前对软件设计的质量进行评估，设计团队可以定义相应的质量标准，软件设计质量评估则按照事先定义的标准进行。

## 软件实现阶段风险分析

### 开发语言不熟悉
软件开发人员对开发语言不熟悉可能会导致学习的成本较高，在预计的学习时间内开发人员无法熟练的掌握相应的开发语言。本次项目使用unity进行开发，由于项目的团队中的大多数人都没有接触过该语言，因此初期的学习成本可能会较高且不易预测，这可能会增加项目的开发时间。

### 开发环境搭建问题
本次项目是一个协同开发项目，项目的开发人员应该搭建统一的开发环境，开发环境的搭建以及开发人员学习使用环境的时间成本暂时无法预料。如果该学习成本较高可能会影响项目的开发时间。
市场风险分析

### 游戏原粉丝抵制
该项目是目前市面上较火的2D游戏“空洞骑士”的粉丝向复刻版，我们大量借鉴了游戏原版的剧情和素材，而原版游戏已经积累了的大量的粉丝，因此游戏的原住粉丝可能会抵制我们的项目。因此，我们的项目需要充分考虑游戏原粉丝的需求，同时也要提高提高项目的质量，努力做到看齐甚至超过原版游戏的程度。

### 同类产品竞争
由于目前市场上同类的2D游戏竞品较多，如果在众多的同类竞品中脱颖而出对于我们的项目来说是一个巨大的挑战。由于本项目是“空洞骑士”的粉丝向复刻版，而原作具有较高的质量并已经积累了大量的粉丝玩家，因此本项目在质量和粉丝方面具有先天的优势。但是本项目也需要具有自己的创新点来满足游戏玩家日益变化的口味。

# 收益分析
《空洞骑士(Hollow Knight)》游戏原作是一款买断制游戏，先后在Steam、任天堂Switch等多个 平台上发售，2019年2月，据开发团队透露，游戏销量已经超过280万份。作为原作的粉丝向复刻游戏， 我们团队也将采用相同的盈利模式，除了买断之外，我们还将推出一些可选的游戏内容下载包 (DLC)，增加新的剧情和关卡，作为扩展内容同时发售。  

## 买断制运营模式
目前市场上盈利较多的游戏主要分为两种:买断式游戏和内购式游戏，本项目完成的游戏属于前
者，主要出于以下方面的考虑:  
- 更好的游戏体验:相比内购式的免费游戏，买断式游戏本身是需要付费的，但是玩家只需要一次消 费，在获取游戏客户端之后，就可以畅玩游戏的所有内容，因此游戏体验更加完整。
- 更公平的游戏氛围:一方面，买断式游戏中不存在氪金玩家和零氪玩家的区别，玩家的所有属性都 是玩家在游戏体验中获得;另一方面，因为游戏本身需要付费，所以提高了外挂成本，一旦封号， 那么游戏账号就会失效。因此相较内购式游戏，买断式游戏对于玩家而言更加公平。
- 单机游戏本身的性质决定的:游戏本身是单机游戏，游戏中大多数时候并不存在与其他玩家的竞 争，允许玩家通过购买道具等加速游戏过程只会降低游戏体验。
- 游戏开发模式决定游戏需要尽可能减少运维成本。内购式游戏需要在游戏开发结束后进行不断更 新。买断式游戏在开发结束后只需要根据市场反馈适当增加游戏内容。因此，我们希望开发买断式 游戏以减少游戏运维和更新的成本。

## DLC收益
除了在游戏平台上发售完整版本的游戏之外，本团队在后期还将开发一到三个额外剧情，作为 DLC
在游戏平台上发售，增加游戏的趣味性，提高玩家的游戏体验。  
DLC的内容包括游戏剧情扩展，玩法扩展以及功能扩展。例如在完整版本内穿插剧情彩蛋，并要求 玩家通过购买DLC的方式获取更多相关的剧情;在DLC中为角色创建更多的操作方式、角色外貌等，增 加游戏体验;提供联网内斗的功能，方便角色之间的互动，增加游戏乐趣。我们的目标是DLC不影响游 戏主体的乐趣，提供游戏主体之外的游戏体验。

## 可能影响收益的因素

### 盗版游戏
 买断式游戏容易遭受非法玩家的破解与修改，从而导致游戏收益的减少，甚至极大影响游戏收
  益。对于这类因素，一方面我们将强化游戏内部的安全机制，增加游戏系统的安全性。另一方面，
  我们也将与游戏平台展开合作，利用游戏平台发布游戏以增加游戏安全。

### 买断制游戏在国内的推行
与内购式游戏相比，对于玩家而言，买断式游戏的门槛更高。很多玩家在买游戏之前，对游戏
  并不十分了解，买断对于他们来说就像是风险投资，很多玩家并不愿意冒险。但是，因为我们的游
  戏本身属于粉丝向复刻游戏，所以可以享受原作带来的红利。

# 成本分析

# 团队介绍

## 团队成员和分工
| 姓名 | 性别 | 职位 | 联系方式 | 职责描述 |
| ----- | ---- | ---- | ------| -------- |
| 丁凡宇 | 男 | 项目经理 | fyding16@fudan.edu.cn | 主角状态和主角动作的设计和编码 |
| 邓朋 | 男 | 项目成员 | pdeng17@fudan.edu.cn | 地图和素材处理 |
| 胡宵宵 | 女 | 项目成员 | xxhu17@fudan.edu.cn | 敌人行为的设计和编码 |
| 金毅铭 | 男 | 项目成员 | ymjin17@fudan.edu.cn | 菜单、存读档、GUI |
| 宋怡景 | 女 | 项目成员 | yjsong17@fudan.edu.cn | 网络部分、排行榜部分 |
| 俞继涛 | 男 | 项目成员 | jtyu17@fudan.edu.cn | 地图和素材处理 |

## 团队优势分析
本团队所有成员均来自复旦大学17级软件工程专业，都是复旦大学卓越工程师计划成员，编程基础 扎实，软件开发经验丰富，熟悉基于 Git 版本控制工具的合作开发流程;在复旦大学浓厚的文化氛围熏 陶下，团队成员的审美水平较高，设计能力较强，团队中均衡的男女比例为项目整体的评估提供了客观 全面的思考视角;除此之外，大学三年的日常相处，团队成员间相处融洽，目标一致，可以确保项目的 高效率推进。  
- 丁凡宇，使用 Unity 引擎进行过类似2D平台跳跃类游戏的开发，对此类游戏的开发流程十分了解， 也能够熟练使用引擎中的各类工具;对项目管理和团队合作开发流程十分熟悉，能够设计游戏架 构，合理分配功能任务，把控项目的开发进度。
- 邓朋，对游戏内地图关卡的设计有独特的理解和把握;编程经验丰富，熟练使用C#语言编程。
- 胡宵宵，游戏经历丰富，能够从已有游戏的成功设计范例中获取经验，可以设计出多种有趣而又难 度适中的关卡。
- 金毅铭，拥有丰富的开发经验，参与了众多web项目构建与实现。编程能力出众，擅长C#编程，能 够熟练使用Unity等开发工具。
- 宋怡景，进行过多个小型web项目的开发，对前后端数据交互十分了解，熟练掌握网络通信相关的 原理。
- 俞继涛，熟练使用 Photoshop、AE 等图像处理工具，掌握大型项目的多种设计模式，擅长C#编 程。

# 项目预计进度计划

 | 时间 | 进度目标 |
 | ---- | --------  |
| 10.12 - 10.18 |分析项目可行性和潜在的风险，完成项目建议书 |  
| 10.19 - 10.25 |工具学习，并各自完成 flappy bird 作为练习 |
| 10.26 - 11.1 |确定项目范围，完成项目框架的搭建 |
| 11.2 - 11.8 |开始具体的编码工作，完成游戏的简易版本 | 
| 11.9 - 11.22 |在简易版本的基础上，完善游戏剧情，优化游戏的UI和交互部分 | 
| 11.23 - 11.29 |完成 DLC 的开发，开发出一到两个额外剧情扩展包 |  
| 11.30 - 12.6 |游戏测试，发布内测版本，修复游戏中的缺陷 |  
| 12.7 - 12.13 |部署并上线游戏和 DLC |
| 12.14 - 12.20 | 完成项目的收尾工作，核实项目质量，整理项目文档 |











